package:
  name: pytensorpipe
  version: 0.0.0

source:
  # TODO: change to official repo once merged
  git_rev: 4a9c3540b028fb2d58f07194d36763445e7e25f8
  git_url: https://github.com/deepsworld/tensorpipe.git

build:
  number: 0
  script: "pip install -v ."	

requirements:
  build:
    - ninja
    - cmake
    - git
    - gxx
    - conda-forge::pybind11
  host:
    - conda-forge::cudatoolkit-dev=11.3
    - pip 
    - python=3.9
  run:
    - pytorch::cudatoolkit=11.3
    - python=3.9

test:
  imports:
    - pytensorpipe

about:
  home: "https://github.com/pytorch/tensorpipe"
  description: "The TensorPipe project provides a tensor-aware channel to transfer rich objects from one process to another while using the fastest transport for the tensors contained therein (e.g., CUDA device-to-device copy)."