package:
  name: pytensorpipe
  version: 0.0.0

source:
  # TODO: change to official repo once merged
  git_rev: 94eb61a79459ab68740073432bc620b5176b3fa7
  git_url: https://github.com/deepsworld/tensorpipe.git

build:
  number: 0
  script: python setup.py install	

requirements:
  build:
    - ninja
    - cmake
    - git
    - gxx
  host:
    - conda-forge::cudatoolkit-dev=11.3
    - pip 
    - conda-forge::pybind11
    - python=3.9
  run:
    - pytorch::cudatoolkit=11.3
    - python=3.9

test:
  imports:
    - pytensorpipe

about:
  home: "https://github.com/pytorch/tensorpipe"
  description: "The TensorPipe project provides a tensor-aware channel to transfer rich objects from one process to another while using the fastest transport for the tensors contained therein (e.g., CUDA device-to-device copy)."